version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: mind
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
