default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port:     <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV.fetch('DB_USER', 'mind') %>

development:
  <<: *default
  database: teams_challenge_development

test:
  <<: *default
  database: teams_challenge_test

production:
  <<: *default
  database: teams_challenge_production
  username: teams_challenge
  password: <%= ENV["TEAMS_CHALLENGE_DATABASE_PASSWORD"] %>
